//-----------------------------------------------------------------------------------------------
// This code was generated by a tool.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//-----------------------------------------------------------------------------------------------

import * as fs from 'fs';
import * as net from 'net';
import { DispatchContext, MyError } from './common';
import { setupServer, shutdownServer } from './common';
import { DefaultImpl, dispatch as dispatchDefault } from './default';

export interface Impl {
    default: DefaultImpl,
}

async function dispatch(ctx: DispatchContext, impl: Impl) {
    if (!ctx.path.startsWith('/v1')) { throw new MyError('not-found', 'invalid invocation version'); }
    const path = ctx.path.substring(3);
    if (path.startsWith('/default/')) { return await dispatchDefault(ctx, impl.default); }
    throw new MyError('not-found', 'invalid invocation');
}

let server: net.Server;
const connections: net.Socket[] = [];
export function initializeWebInterface(impl: Impl) {
    server = net.createServer();
    setupServer(server, connections, dispatch, impl);
    if (fs.existsSync('/tmp/fine-wacq.socket')) {
        fs.unlinkSync('/tmp/fine-wacq.socket');
    }
    server.listen('/tmp/fine-wacq.socket');
}
export function shutdownWebInterface(): Promise<void> {
    return shutdownServer(server, connections);
}
