//-----------------------------------------------------------------------------------------------
// This code was generated by a tool.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//-----------------------------------------------------------------------------------------------

import { get, post } from '../adk/api-client';
import type { Message } from './types';

export const $default = {
    getRecentPrivates: (): Promise<number[]> => get(`/wacq/v1/default/recentPrivates`),
    getRecentGroups: (): Promise<number[]> => get(`/wacq/v1/default/recentGroups`),
    getPrivateRecentMessages: (privateId: number): Promise<Message[]> => get(`/wacq/v1/default/privateRecentMessages/${privateId}`),
    getGroupRecentMessages: (groupId: number): Promise<Message[]> => get(`/wacq/v1/default/groupRecentMessages/${groupId}`),
    sendPrivateMessage: (message: Message): Promise<Message> => post(`/wacq/v1/default/sendPrivateMessage`, message),
    sendGroupMessage: (message: Message): Promise<Message> => post(`/wacq/v1/default/sendGroupMessage`, message),
};
