//-----------------------------------------------------------------------------------------------
// This code was generated by a tool.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//-----------------------------------------------------------------------------------------------

import { FineError } from '../../adk/error';
import { ForwardContext, Context } from '../../adk/api-server';
import { validateId, validateNumber, validateBody } from '../../adk/api-server';
import type { Message } from '../types';

export interface DefaultImpl {
    getRecentPrivates: (ctx: Context) => Promise<number[]>,
    getRecentGroups: (ctx: Context) => Promise<number[]>,
    getPrivateRecentMessages: (privateId: number, ctx: Context) => Promise<Message[]>,
    getGroupRecentMessages: (groupId: number, lastTime: number, ctx: Context) => Promise<Message[]>,
    sendPrivateMessage: (message: Message, ctx: Context) => Promise<Message>,
    sendGroupMessage: (message: Message, ctx: Context) => Promise<Message>,
}

export async function dispatch(ctx: ForwardContext, impl: DefaultImpl): Promise<void> {
    let match: RegExpExecArray;
    const methodPath = `${ctx.method} ${ctx.path.slice(11)}`;

    match = /^GET \/recentPrivates$/.exec(methodPath); if (match) {
        ctx.body = await impl.getRecentPrivates(ctx.state);
        return;
    }
    match = /^GET \/recentGroups$/.exec(methodPath); if (match) {
        ctx.body = await impl.getRecentGroups(ctx.state);
        return;
    }
    match = /^GET \/privateRecentMessages\/(?<privateId>\d+)$/.exec(methodPath); if (match) {
        ctx.body = await impl.getPrivateRecentMessages(validateId('privateId', match.groups['privateId']), ctx.state);
        return;
    }
    match = /^GET \/groupRecentMessages\/(?<groupId>\d+)\/(?<lastTime>\d+)$/.exec(methodPath); if (match) {
        ctx.body = await impl.getGroupRecentMessages(validateId('groupId', match.groups['groupId']), validateNumber('lastTime', match.groups['lastTime']), ctx.state);
        return;
    }
    match = /^POST \/sendPrivateMessage$/.exec(methodPath); if (match) {
        ctx.body = await impl.sendPrivateMessage(validateBody(ctx.body), ctx.state);
        ctx.status = 201;
        return;
    }
    match = /^POST \/sendGroupMessage$/.exec(methodPath); if (match) {
        ctx.body = await impl.sendGroupMessage(validateBody(ctx.body), ctx.state);
        ctx.status = 201;
        return;
    }

    throw new FineError('not-found', 'invalid invocation');
}
